import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { NavBar } from "@/components/Navbar/NavBar";
import { I18nProvider } from "@/provider/I18nProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <I18nProvider locale={locale}>
          <SessionProvider session={session}>
            <NavBar />
            {children}
          </SessionProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
